var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[...all]/route.js")
R.c("server/chunks/[root-of-the-server]__0l7~bhl._.js")
R.c("server/chunks/01vs_next_dist_009~_h~._.js")
R.c("server/chunks/0aee_@better-auth_core_dist_08seeik._.js")
R.c("server/chunks/0mpx_better-auth_dist_04vn889._.js")
R.c("server/chunks/07uu_kysely_dist_operation-node_0wsmst6._.js")
R.c("server/chunks/07uu_kysely_dist_query-builder_0xbocfv._.js")
R.c("server/chunks/07uu_kysely_dist_schema_0.c13bl._.js")
R.c("server/chunks/07uu_kysely_dist_13c3xm_._.js")
R.c("server/chunks/12gq_jose_dist_webapi_0pk_2nw._.js")
R.c("server/chunks/0rgj_zod_v4_0go9h72._.js")
R.c("server/chunks/0_1r_drizzle-orm_0y5omwc._.js")
R.c("server/chunks/0edt_@neondatabase_serverless_index_mjs_03lvu6c._.js")
R.c("server/chunks/[root-of-the-server]__02n58j8._.js")
R.c("server/chunks/[root-of-the-server]__09kpn_f._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_[___all]_route_actions_066ldxc.js")
R.m("[project]/node_modules/.pnpm/next@16.2.6_@babel+core@7.29.7_react-dom@19.2.4_react@19.2.4__react@19.2.4/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/[...all]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/.pnpm/next@16.2.6_@babel+core@7.29.7_react-dom@19.2.4_react@19.2.4__react@19.2.4/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/[...all]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
