var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/calendar/route.js")
R.c("server/chunks/app_api_calendar_route_ts_0-v1ko6._.js")
R.c("server/chunks/01vs_next_0~zeytc._.js")
R.c("server/chunks/0_1r_drizzle-orm_0y5omwc._.js")
R.c("server/chunks/0edt_@neondatabase_serverless_index_mjs_03lvu6c._.js")
R.c("server/chunks/[externals]_pg_0ot~j7s._.js")
R.c("server/chunks/[root-of-the-server]__0en-fig._.js")
R.c("server/chunks/_next-internal_server_app_api_calendar_route_actions_0_x_bdn.js")
R.m("[project]/node_modules/.pnpm/next@16.2.6_@babel+core@7.29.7_react-dom@19.2.4_react@19.2.4__react@19.2.4/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/calendar/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/.pnpm/next@16.2.6_@babel+core@7.29.7_react-dom@19.2.4_react@19.2.4__react@19.2.4/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/calendar/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
